version: "3.8"
services:
  mongo:
    image: mongo:5
    ports:
      - "9009:27017"
    volumes:
      - database:/data/db
    networks:
      - signatureapp

  back:
    build:
      context: ./signatureServer/
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_NAME=signatureapp
      - DB_URL=mongodb://mongo
      - IMG_LINK=http://51.38.125.78/api/img/
      - PDF_LINK=http://51.38.125.78/api/files/
      - REFRESH_TOKEN_SECRET=refreshToken
      - ACCESS_TOKEN_SECRET=accessToken
      - EMAIL=ghassen.klai@esprit.tn
      - pwd= ***** 
    ports:
      - "3000:3000"
    networks:
      - signatureapp
    volumes:
      - files:/home/node/app/public
    depends_on:
      - mongo

  front:
    build:
      context: ./esprit_signature/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - signatureapp
    environment:
      - endpoints=http://51.38.125.78/api/
    depends_on:
      - back

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
    networks:
      - signatureapp
    depends_on:
      - front
      - back
      - mongo

volumes:
  database:
  files:

networks:
  signatureapp:
