version: "1"
services:
  mongo:
    image: mongo:5
    ports:
      - "9009:27017"
    volumes:
      - database:/data/db
      - files:/public
    networks:
      - signatureapp

  back:
    build:
      context: ./signatureServer/ 
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_NAME=signatureapp
      - DB_URL=mongodb://mongo
      - IMG_LINK=http://51.38.125.78:3000/img/
      - PDF_LINK=http://51.38.125.78:3000/files/
      - REFRESH_TOKEN_SECRET=refreshToken
      - ACCESS_TOKEN_SECRET=accessToken	
    ports:
      - "3000:3000"
    networks:
      - signatureapp
    depends_on:
      - mongo

  front:
    build:
      context: ./flutter-node-server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - signatureapp
    depends_on:
      - back

volumes:
  database:
  files:

networks:
  signatureapp:
