import { MongoClient } from "mongodb";

import dotenv from "dotenv";
dotenv.config({ path: "../.env" });

const teachers = [
  {
    matricule: "0000",
    fullName: "admin admin",
    email: "admin.admin@esprit.tn",
    role: "ADMIN",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0037",
    fullName: "JEDIDI HASSEN",
    email: "hassen.jedidi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0062",
    fullName: "BEN FADHEL SANA",
    email: "sana.benfadhel@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0071",
    fullName: "OUAFI Ramzi",
    email: "ramzi.ouafi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0074",
    fullName: "BESSAIES MARIAM",
    email: "mariam.bessaies@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0099",
    fullName: "ZERAI MOURAD",
    email: "mourad.zerai@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0111",
    fullName: "JGUIRIM NABIL",
    email: "nabil.jguirim@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0135",
    fullName: "SIFI SAMI",
    email: "sami.sifi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0136",
    fullName: "CHEKIR MERIEM",
    email: "meriem.chekir@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0137",
    fullName: "MTAR FAYCEL",
    email: "faycel.mtar@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0139",
    fullName: "HACHANI  ABDERRAZEK",
    email: "abderrazek.hachani@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0148",
    fullName: "BERHOUMA EP REDISSI HAJER",
    email: "hajer.berhouma@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0152",
    fullName: "ZOUAOUI ANIS",
    email: "anis.zouaoui@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0160",
    fullName: "LOUATI EPOUSE AKROUT KAOUTHER",
    email: "kaouther.louati@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0210",
    fullName: "HAJJEM SALMA",
    email: "salma.hajjem@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0216",
    fullName: "ESSADDI SHEMA",
    email: "shema.essaddi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0218",
    fullName: "FREFITA RIADH",
    email: "riadh.frefita@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0285",
    fullName: "DAMERGI Ep ESSID Ashraf",
    email: "ashraf.damergi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0288",
    fullName: "HAMMOUDA Zouhour",
    email: "zouhour.hammouda@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0291",
    fullName: "KAROUI SYRINE",
    email: "syrine.karoui@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0305",
    fullName: "BDIWI RAWIA",
    email: "rawia.bdiwi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0308",
    fullName: "CHERNI THAMEUR",
    email: "thameur.cherni@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0320",
    fullName: "BOUHAOUEL RIM",
    email: "rim.bouhaouel@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0321",
    fullName: "MESBAH  SONIA",
    email: "sonia.mesbeh@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0325",
    fullName: "BOURAOUI RAHMA",
    email: "rahma.bouraoui@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0336",
    fullName: "Slimen Ines",
    email: "ines.slimen@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0338",
    fullName: "CHAOUACHI  Taoufik ",
    email: "taoufik.chaouachi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0342",
    fullName: "GHARBI MAJDI",
    email: "majdi.gharbi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0346",
    fullName: "GARGOURI KARRAY",
    email: "karray.gargouri@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0350",
    fullName: "MBAREK SOUMAYA",
    email: "soumaya.mbarek@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0356",
    fullName: "MADHIOUB MANEL",
    email: "\tmanel.madhioub@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0359",
    fullName: "CHOUCHANE EP TARROUCHE  INES",
    email: "ines.chouchane@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0367",
    fullName: "BOUAKLINE MOHAMED ALI",
    email: "mohamedali.bouakline@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0389",
    fullName: "TEBER FATEN",
    email: "feten.teber@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0391",
    fullName: "MHAYA INES",
    email: "ines.mhaya@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0393",
    fullName: "GUEBEBIA IMEN",
    email: "imen.guebebia@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0394",
    fullName: "SLIMANE EP GUIZA NADA",
    email: "nada.slimane@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0398",
    fullName: "DCHICHA MABROUKA",
    email: "mabrouka.dchicha@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0400",
    fullName: "TOUMI EP AJMI SAFA",
    email: "safa.toumi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0405",
    fullName: "MARZOUK AHLEM",
    email: "ahlem.marzouk@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0407",
    fullName: "LOUATI EP ABID FATMA",
    email: "fatma.louati@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0412",
    fullName: "BEN AMARA FARES",
    email: "fares.benamara@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0413",
    fullName: "EL MKHININI MAHER",
    email: "maher.mkhinni@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0414",
    fullName: "SADDEM BRAHIM",
    email: "brahim.saddem@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0428",
    fullName: "CHANNOUFI INES",
    email: "ines.channoufi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0429",
    fullName: "LAABIDI HOUDA",
    email: "houda.abidi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0433",
    fullName: "BAGGA SABRINE",
    email: "sabrine.bagga@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0446",
    fullName: "HJIRI WIEM",
    email: "wiem.hjiri@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0501",
    fullName: "BEN AHMED ZIED",
    email: "zied.benahmed@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0521",
    fullName: "HAMMAMI EP ESGHAIER  AMAL",
    email: "amal.hammami@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0538",
    fullName: "BOUSAA YASSINE",
    email: "yassine.boussaa@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0539",
    fullName: "ZIEDIA ABDELKADER",
    email: "abdelkader.ziedia@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0540",
    fullName: "BOUGHOULA ANOUARE",
    email: "anouare.boughoula@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0541",
    fullName: "NEJI WISSAL",
    email: "wissal.neji@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0544",
    fullName: "SEBAI MANEL",
    email: "manel.sebai@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0549",
    fullName: "ALOUANE RYM",
    email: "rym.alouane@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0578",
    fullName: "TRABELSI WIEM",
    email: "wiem.trabelsi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0579",
    fullName: "BOUSBIA SALAH",
    email: "salah.bousbia@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0580",
    fullName: "BATIS SONIA",
    email: "sonia.batis@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0585",
    fullName: "BELAID BOUMAIZA WAFA",
    email: "wafa.boumaiza@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0586",
    fullName: "KAMEL INOUBLI AMIRA",
    email: "amira.kamelinoubli@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0587",
    fullName: "MELLITI EP BEN KHEDHER Dhouha",
    email: "dhouha.melliti@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0589",
    fullName: "REJEB Nejla",
    email: "nejla.rejeb@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0591",
    fullName: "LABBANE MOHAMED WALID",
    email: "walid.labbane@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0596",
    fullName: "JEDIDI LINDA",
    email: "linda.jedidi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0597",
    fullName: "MESSAOUDI YOSRA",
    email: "yosra.messaoudi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0608",
    fullName: "LOUATI MAROUA",
    email: "maroua.louati@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0611",
    fullName: "KOCHBATI IMEN",
    email: "imen.kochbati@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0612",
    fullName: "JAZIRI MAHER",
    email: "meher.jaziri@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0627",
    fullName: "GHOZZI YOSR",
    email: "yosr.ghozzi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0652",
    fullName: "TEBOURBI FATEN",
    email: "feten.tebourbi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0654",
    fullName: "MNAKBI AMEL",
    email: "amel.mnakbi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0663",
    fullName: "BETTAIEB SOUHA",
    email: "souha.bettayeb@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0665",
    fullName: "SOUAKI GHOFRANE",
    email: "ghofrane.souaki@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0674",
    fullName: "BEL HADJ DAOUED SINDA",
    email: "sinda.belhajdaoud@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0675",
    fullName: "ROMMENE AMENI",
    email: "ameni.rommene@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0679",
    fullName: "DOUIRI MAROUA",
    email: "maroua.douiri@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0719",
    fullName: "BEN MARDES ACHREF",
    email: "achref.benmerdes@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0736",
    fullName: "BEN LASMAR MOHAMED ANIS",
    email: "mohamedanis.benlasmar@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0737",
    fullName: "ZOUARI TALEL",
    email: "talel.zouari@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0738",
    fullName: "FERSI KMAR",
    email: "kmar.fersi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0741",
    fullName: "ZOGHLEMI MERIEM",
    email: "mariem.zoghlemi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0743",
    fullName: "BEN SAID ZAINEB",
    email: "zeineb.bensaid@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0746",
    fullName: "CHAOUACHI MANEL",
    email: "manel.chaouachi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0753",
    fullName: "DOUSS RIM",
    email: "rim.douss@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0755",
    fullName: "BEN CHAABANE SOUMAYA",
    email: "soumaya.benchaabane@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0756",
    fullName: "OUALI YOSRA",
    email: "yosra.ouali@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0757",
    fullName: "RIAHI MOHAMED HEDI",
    email: "mohamedhedi.riahi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0773",
    fullName: "MARROUKI AMINE",
    email: "amine.marrouki@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0781",
    fullName: "DEBBABI NEHLA",
    email: "nehla.debbabi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0784",
    fullName: "BEN MOUSSA HEND",
    email: "hend.benmoussa@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0797",
    fullName: "TLILI RYM",
    email: "rim.tlili@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0821",
    fullName: "ZEMZEM AMINA",
    email: "amina.zemzem@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0835",
    fullName: "CHAABANI HAZAR",
    email: "hazar.chaabani@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0847",
    fullName: "EL GHOUL IMENE",
    email: "imene.elghoul@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0850",
    fullName: "AJAILIA NADIA",
    email: "nadia.ajailia@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0856",
    fullName: "MARZOUGUI ONS",
    email: "ons.marzougui@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0874",
    fullName: "AOUN BOUTHEINA AMINA",
    email: "amina.aoun@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0876",
    fullName: "ZGHAL MOHAMED KHALIL",
    email: "mohamedkhalil.zghal@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0879",
    fullName: "REZGUI JIHENE",
    email: "jihen.rezgui@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0881",
    fullName: "ARFAOUI Dhouha",
    email: "dhouha.arfaoui@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0882",
    fullName: "SELMI AYMEN",
    email: "aymen.esselmi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0912",
    fullName: "MHADHBI SAFA",
    email: "safa.mhadhbi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0915",
    fullName: "BEJI AFIF",
    email: "afif.beji@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0921",
    fullName: "GANNOUN MAROUA",
    email: "maroua.ganoun@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0943",
    fullName: "BOUHDID Badiaa",
    email: "badiaa.bouhdid@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0946",
    fullName: "OTHMANI Anissa",
    email: "anissa.othmani@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0948",
    fullName: "FOURATI Hend",
    email: "hend.fourati@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0954",
    fullName: "BEN ABDELHAMID  Manel",
    email: "manel.benabdelhamid@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0955",
    fullName: "BRIK  Adel",
    email: "adel.brik@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0957",
    fullName: "KAROUI Asma",
    email: "asma.karoui@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0958",
    fullName: "KERFAI Nejla",
    email: "nejla.kerfai@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0959",
    fullName: "KALLEL  Taheni",
    email: "taheni.kallel@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0967",
    fullName: "MAALAOUI Hiba",
    email: "hiba.maalaoui@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0970",
    fullName: "LASMAR SAFA",
    email: "safa.lasmar@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "0971",
    fullName: "ISMAIL EP YOUSSEF SARRA",
    email: "sarra.ismail@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1002",
    fullName: "EL MERAI Meriem",
    email: "mariem.merai@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1021",
    fullName: "SAMET Nouha",
    email: "nouha.samet@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1027",
    fullName: "AYARI Asma",
    email: "asma.ayari@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1032",
    fullName: "AOUINI Imen",
    email: "imen.aouini@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1033",
    fullName: "BERRAHAL Sarra",
    email: "sarra.berrahal@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1036",
    fullName: "SASSI Soumaya",
    email: "soumaya.sassi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1037",
    fullName: "HASSINI Mourad",
    email: "mourad.hassini@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1040",
    fullName: "LAHMAR Hiba",
    email: "hiba.lahmer@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1041",
    fullName: "HAJJI EP CHAMAKHI Amel",
    email: "amel.hajjichammakhi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1047",
    fullName: "RIAHI EP TEKAYA Insaf",
    email: "insaf.tekaya@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1048",
    fullName: "MRABET  Abir",
    email: "abir.mrabet@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1049",
    fullName: "HASSIN Aymen",
    email: "aymen.hassin@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1051",
    fullName: "GAIGI EP GHOZZI Wafa",
    email: "wafa.gaigi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1053",
    fullName: "BEN ELOUEFI Rim",
    email: "rim.benelouefi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1055",
    fullName: "KHEDHRI IMED",
    email: "imed.khedhri@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1057",
    fullName: "BEN AZIZA Sahar",
    email: "sahar.benaziza@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1058",
    fullName: "JMAL Yosra ",
    email: "yosra.jmal@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1062",
    fullName: "SOUISSI  Mayssa",
    email: "mayssa.souissi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1064",
    fullName: "B HASSEN JILANI BEN NAOUARA Nouridine ",
    email: "noureddine.jilani@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1068",
    fullName: "DERBEL EP TABBESSI Zeineb",
    email: "zeineb.derbel@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1071",
    fullName: "ARGOUBI Soumaya",
    email: "soumaya.argoubi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1085",
    fullName: "AYED Sawsen",
    email: "sawssen.ayed@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1092",
    fullName: "CHEBBI Mohamed Amine",
    email: "mohamedamine.chebbi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1095",
    fullName: "EL ADDED Maha",
    email: "maha.added@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1103",
    fullName: "ABIDI Sarra",
    email: "sarra.abidi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1104",
    fullName: "JELIDI Farouk",
    email: "farouk.jelidi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1105",
    fullName: "EL MEJID Ines",
    email: "ines.elmejid@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1106",
    fullName: "TOUATI Nahla",
    email: "nehla.kermani@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1107",
    fullName: "SOUIBGUI Meriem",
    email: "meriem.souibgui@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1109",
    fullName: "ZIADI Faten",
    email: "faten.ziadi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1129",
    fullName: "ABDAOUI Noura",
    email: "Noura.ABDAOUI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1133",
    fullName: "JBALIA Aymen",
    email: "Aymen.JBALIA@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1134",
    fullName: "ALLANI Anissa",
    email: "Anissa.ALLANI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1136",
    fullName: "AMMAR DAOUD Marwa",
    email: "Marwa.AMMARDAOUD@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1139",
    fullName: "CHAMEKH Marwa",
    email: "Marwa.CHAMEKH@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1140",
    fullName: "FARHAT Sondes",
    email: "Sondes.FARHAT@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1144",
    fullName: "LEMJID Achref",
    email: "Achref.LEMJID@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1145",
    fullName: "AISSA Abdelmonem",
    email: "Abdelmonem.AISSA@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1146",
    fullName: "BEN SALAH Ons",
    email: "ons.bensalah@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1147",
    fullName: "GHALLEB Fakhreddine",
    email: "Fakhreddine.GHALLEB@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1148",
    fullName: "KHEMIRI Zied",
    email: "Zied.KHEMIRI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1149",
    fullName: "BOUZOUITA Mariem",
    email: "Mariem.BOUZOUITA@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1150",
    fullName: "SBISSI Samia",
    email: "Samia.SBISSI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1151",
    fullName: "LOUSSIFI Hichem",
    email: "Hichem.LOUSSIFI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1152",
    fullName: "DHAOUADI Rahma",
    email: "Rahma.DHAOUADI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1154",
    fullName: "AMRI Rahma",
    email: "Rahma.AMRI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1155",
    fullName: "CHERIF Safa",
    email: "safa.zhiouacherif@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1156",
    fullName: "AYARI Tarek",
    email: "Tarek.AYARI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1160",
    fullName: "GLIOUEZ Souhir",
    email: "Souhir.GLIOUEZ@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1161",
    fullName: "OUERFELLI Linda",
    email: "linda.OUERFELLI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1162",
    fullName: "BEN YAHIA Mohamed Selmene",
    email: "medselmene.benyahia@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1165",
    fullName: "TOUIL Mohamed Amine ",
    email: "mohamedamine.touil@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1166",
    fullName: "BOUKHRIS Islem",
    email: "islem.boukhris@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1167",
    fullName: "GHORBEL Ali",
    email: "ali.ghorbel@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1169",
    fullName: " HATTAB EP Ghalleb Sondes",
    email: "sondes.hattab@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1170",
    fullName: "MASSOUDI Radhouene",
    email: "radhouane.MASSOUDI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1174",
    fullName: "GHARSALLI Mounira",
    email: "mounira.gharsalli@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1177",
    fullName: "FAYECHI Sana",
    email: "sana.fayechi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1182",
    fullName: "EL HEDHLI  Amel ",
    email: "amel.hedhli@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1190",
    fullName: "CHAGTMI Nadia",
    email: "nadia.chagtmi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1191",
    fullName: "NAOUAR Nesrine",
    email: "nesrine.naouar@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1193",
    fullName: "GRITLI Wafa",
    email: "wafa.gritli@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1203",
    fullName: "MBARKI Wajih",
    email: "wajih.mbarki@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1204",
    fullName: "CHARFI Bilel",
    email: "bilel.charfi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1205",
    fullName: "MESSAOUDI Hafawa",
    email: "hafawa.messaoudi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1206",
    fullName: "BRAIEK Hamdi",
    email: "hamdi.houichet@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1208",
    fullName: "MATHLOUTHI Wided",
    email: "wided.mathlouthi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1209",
    fullName: "FERJANI Rahma",
    email: "rahma.ferjani@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1210",
    fullName: "CHERIF Sami",
    email: "sami.cherif1@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1221",
    fullName: "LAMINE Ameni",
    email: "amani.lamine@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1228",
    fullName: "TAKROUNI Manel",
    email: "manel.takrouni@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1235",
    fullName: "KOLSI Mohamed",
    email: "mohamed.kolsi1@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1237",
    fullName: "SAIDANI Lassad",
    email: "lassaad.saidani@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1249",
    fullName: "BEN KAHLA Radhwen",
    email: "radhwen.benkahla@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1252",
    fullName: "MALLEK  MAHA ",
    email: "maha.mallek@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1258",
    fullName: "GDHAMI ASMA",
    email: "asma.ghdami@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1259",
    fullName: "KCHAW  MARWA ",
    email: "marwa.kchaou@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1260",
    fullName: "AYADI Mohamed Ali",
    email: "medali.ayadi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1271",
    fullName: "HAMOUDA GHASSEN",
    email: "ghassen.hammouda@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1282",
    fullName: "KSENTINI AMEL",
    email: "amel.ksentini@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1283",
    fullName: "TOUITI EP BEN KHALIFA SOUKEINA FATIMA",
    email: "soukeina.touiti@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1285",
    fullName: "HAOUEL MOHAMED",
    email: "mohamed.haouel@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1286",
    fullName: "NHERI SOUMAYA",
    email: "soumaya.nheri@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1292",
    fullName: "GHARSSALLAH ZAINEB ",
    email: "zeineb.gharsallah@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1293",
    fullName: "HECHMI Mohamed Amine",
    email: "mohamedamine.hechmi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1295",
    fullName: "MAHAT Emna ",
    email: "emna.mahat@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1297",
    fullName: "OTHMANI Halima",
    email: "halima.othmani@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1298",
    fullName: "BELKNENI Maroua",
    email: "maroua.belkneni@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1299",
    fullName: "HASNAOUI Marwa",
    email: "hasnaoui.marwa@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1301",
    fullName: "Allaya Aida",
    email: "aida.allaya@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1303",
    fullName: "MEJRI Ameni",
    email: "ameni.mejri@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1304",
    fullName: "GUESMI Latifa",
    email: "latifa.guesmi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1305",
    fullName: "BEN HADJ KHLIFA Meriem",
    email: "meriem.benhadjkhlifa@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1312",
    fullName: "KAOUACH Ines",
    email: "ines.kaouach@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1314",
    fullName: "LASSOUED Donia",
    email: "donia.lassoued@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1318",
    fullName: " BDIWI  Rim",
    email: "rim.bdiwi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1319",
    fullName: "HLEL  Jihene",
    email: "jihene.hlel@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1321",
    fullName: "WALI  Rawia",
    email: "rawia.wali@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1337",
    fullName: "ELLOUZE Ameni",
    email: "ameni.ellouze@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1338",
    fullName: "BEL HADJ HASSIN  Anis",
    email: "anis.belhadjhassin@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1339",
    fullName: "BEN KHALIFA Ghada",
    email: "ghada.benkhalifa@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1341",
    fullName: "BANI  Hela ",
    email: "hella.bani@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1342",
    fullName: "CHEBBI Mohsen",
    email: "mohsen.chebbi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1343",
    fullName: "GHORBEL  EMNA",
    email: "emna.ghorbel@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1344",
    fullName: "MERSANI AMANI",
    email: "ameni.mersani@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1345",
    fullName: "RIHANI Amal",
    email: "amal.rihani@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1346",
    fullName: "BOUSELMI Souha",
    email: "souha.bousselmi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1349",
    fullName: "BEN MANSOUR  Hana ",
    email: "hana.benmansour@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1351",
    fullName: "Guedria Khaled",
    email: "khaled.guedria@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1352",
    fullName: "Hamrouni Mohamed Khaled",
    email: "medkhaled.hamrouni@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1355",
    fullName: "NAIFER Sirine ",
    email: "sirine.naifer@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1356",
    fullName: "ZAABOUTI Sirine ",
    email: "sirine.zaabouti@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1358",
    fullName: "LAABIDI Zaineb",
    email: "zaineb.labidi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1360",
    fullName: "ZAOUGA WIEM",
    email: "wiem.zaouga@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1371",
    fullName: "ABIDI Yassine ",
    email: "yassine.abidi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1372",
    fullName: "JOUINI Ilhem",
    email: "ilhem.jouini@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1374",
    fullName: "LAYOUNI Olfa",
    email: "olfa.laayouni@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1381",
    fullName: "BEN SLIMEN Nouha ",
    email: "nouha.benslimen@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1388",
    fullName: "HOSNI Mohamed",
    email: "mohamed.hosni@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1396",
    fullName: "ZEYDI Asma",
    email: "asma.zeydi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1398",
    fullName: "NATCHAOUI Sana",
    email: "sana.natchaoui@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1400",
    fullName: "RABHI KAOUTHER",
    email: "kawther.rabhi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1401",
    fullName: "HARRABI MADIHA",
    email: "Madiha.HARRABI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1402",
    fullName: "GUESMI SOUMAYA",
    email: "guesmi.soumaya@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1405",
    fullName: "MOUSSA SONIA",
    email: "sonia.moussa@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1406",
    fullName: "ELHAMMI MOHAMED",
    email: "mohamed.ELHAMMI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1407",
    fullName: "AYARI  Salma",
    email: "salma.ayari@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1408",
    fullName: "LAMINE  Salem",
    email: "salem.lamine@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1409",
    fullName: "HAMOUDI Najet",
    email: "najet.hammouda@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1410",
    fullName: "BASTI Safa",
    email: "safa.basti@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1411",
    fullName: "GHANMI Chifaa",
    email: "chifaa.ghanmi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1412",
    fullName: "AMARA Aya",
    email: "Aya.AMARA@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1413",
    fullName: "AMOR BEN ALI  Abir",
    email: "abir.amorbenali@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1415",
    fullName: "BESSADOK Khadija",
    email: "khadija.bessadak@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1416",
    fullName: "ZORGUI Myriam",
    email: "mariem.zorgui@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1417",
    fullName: "AYED Hela",
    email: "hela.ayed@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1419",
    fullName: "BOUALI Marwa",
    email: "marwa.bouali@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1420",
    fullName: "BOUSLEMA Chedy",
    email: "chedy.BOUSLEMA@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1421",
    fullName: "HAJJAJI YOSRA",
    email: "yosra.hajjaji@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1423",
    fullName: "SAOUDI SAFA",
    email: "safa.saoudi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1425",
    fullName: "DOGHRI Wael",
    email: "wael.doghri@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1426",
    fullName: "SELLAMI OUSSEMA",
    email: "oussema.sellami@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1427",
    fullName: "TRABELSI Imene",
    email: "imene.trabelsi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1429",
    fullName: "HADJ SASSI  Esleme",
    email: "Esleme.HadjSASSI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1430",
    fullName: "BEN HAJ YOUSSEF Anis",
    email: "anis.hajyoussef@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1432",
    fullName: "SAIDANI Asma",
    email: "saidani.asma@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1433",
    fullName: "BOUZID Mouna",
    email: "mouna.bouzid@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1435",
    fullName: "CHEHIBI Manel",
    email: "manel.chehibi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1436",
    fullName: "MEGUEBLI Yosra",
    email: "yosra.meguebli@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1437",
    fullName: "MOUMNI Hatem",
    email: "hatem.moumni@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1448",
    fullName: "BEN AROUS ABDERAHMEN",
    email: "abderrahmen.benarous@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1452",
    fullName: "BORGHOL Riham",
    email: "riham.BORGHOL@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1454",
    fullName: "GHRIBI RIM",
    email: "rim.ghribi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1455",
    fullName: "BEN GHARBIA  Imene",
    email: "imene.bengharbia@esprit.TN",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1456",
    fullName: "FRAIJI  Yosra ",
    email: "yosra.fraiji@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1457",
    fullName: "SARDOUK Chahnez",
    email: "chahnez.sardouk@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1458",
    fullName: "LAKHDHAR Saoussen",
    email: "saoussen.lakhdhar@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1459",
    fullName: "CHAMEKHI Skander ",
    email: "skander.chamakhi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1462",
    fullName: "BELLAAJ  Maha",
    email: "maha.bellaaj@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1463",
    fullName: "BOUSLAHI Hamdi",
    email: "hamdi.bouslehi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1464",
    fullName: "ABDELLAOUI Nader ",
    email: "nader.abdellaoui@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1465",
    fullName: "KHAMASSI Manel ",
    email: "manel.khamassi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1466",
    fullName: "IBN ELFEKIH Oumeima",
    email: "oumeima.ibnelfekih@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1467",
    fullName: "BOUAZIZI Nesrine",
    email: "nesrine.bouazizi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1471",
    fullName: "HZAIEM Abir",
    email: "abir.hzaiem@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1472",
    fullName: "SAADAOUI Skander ",
    email: "skander.saadaoui@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1474",
    fullName: "FODHA  Ghassen",
    email: "ghassen.fodha@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1485",
    fullName: "BEN NCIRA Amel ",
    email: "amel.bennicira@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1486",
    fullName: "DRISS Ameni",
    email: "ameni.driss@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1487",
    fullName: "HOUILMI Chaima ",
    email: "chaima.houimli@esprit.tn ",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1488",
    fullName: "BEN BELGACEM Ghada",
    email: "ghada.benbelgacem@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1490",
    fullName: "SASSI Jamila",
    email: "jamila.sassi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1491",
    fullName: "DHAMER Karima ",
    email: "karima.dhamer@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1492",
    fullName: "BEN SALEM Mariem",
    email: "bensalem.mariem@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1494",
    fullName: "HMAYDA  Mounira ",
    email: "mounira.hmayda@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1495",
    fullName: "GASMI Oumayma ",
    email: "oumayma.guasmi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1496",
    fullName: "EL WARGHAMMI Radhia",
    email: "radhia.werghemmi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1497",
    fullName: "CHAARI  Rihab",
    email: "rihab.chaari@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1499",
    fullName: "BOUCHOUCHA Yosra",
    email: "yosra.bouchoucha@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1500",
    fullName: "MANNOUBI Yosra ",
    email: "yosra.mannoubi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1501",
    fullName: "MEJRI Youssef",
    email: "mejri.youssef@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1504",
    fullName: "MEJRI Hela",
    email: "hela.mejri@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1507",
    fullName: "BEN SALAH Noura",
    email: "noura.bensalah@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1515",
    fullName: "SOMAI  RIM",
    email: "rim.somai@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1516",
    fullName: "ZAOUGA Aziza",
    email: "aziza.zaouga@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1520",
    fullName: "ROUISSI Ines",
    email: "ines.rouissi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1525",
    fullName: "HACHANI Safa",
    email: "safa.hachani@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1526",
    fullName: "DAKHLI Imen",
    email: "imen.dakhli@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1527",
    fullName: "TRABELSI  Mustapha",
    email: "mustapha.trabelsi1@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1528",
    fullName: "NASSIB AHLEM",
    email: "NESSIB.AHLEM@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1529",
    fullName: "AGREBI NOUR",
    email: "AGERBI.NOUR@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1530",
    fullName: "TEBOURSKI Farah",
    email: "farah.tebourski@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1531",
    fullName: "OUESLATI AMEL",
    email: "AMEL.OUESLATI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1532",
    fullName: "SAHRAOUI Arwa",
    email: "aroua.sahraoui@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1533",
    fullName: "ALKHAYAT SALMA",
    email: "salma.alkhayat@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1534",
    fullName: "HRIZI  Dorsaf",
    email: "DORSAF.HRIZI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1535",
    fullName: "ESSAFI SARRA",
    email: "SARRA.ESSAFI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1536",
    fullName: "BOUZID Yosra",
    email: "YOSRA.BOUZID@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1537",
    fullName: "SAIHI MARWA",
    email: "SAIHI.MARWA@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1538",
    fullName: "MNASSRI AYMEN",
    email: "aymen.mnasri@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1539",
    fullName: "DZIRI MONGI",
    email: "mongi.dziri@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1540",
    fullName: "AMMAR AHMED",
    email: "ammar.ahmed@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1541",
    fullName: "OUNI EP MEZNI HIBA",
    email: "hiba.ouni@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1542",
    fullName: "BEN CHEIKH AMAL",
    email: "amal.benchikh@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1543",
    fullName: "JENDOUBI EP LACHNAB HOUDA",
    email: "houda.jendoubi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1544",
    fullName: "ABBASSI BOUTHEINA",
    email: "boutheina.abassi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1545",
    fullName: "RAISSI EP DHAHRI KHADIJA",
    email: "khadija.raissi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1546",
    fullName: "ZOUAIDI SOUKEINA",
    email: "ZOUAIDA.SOUKEIKA@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1547",
    fullName: "TRABELSI Wiem ",
    email: "trabelsi.wiem@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1548",
    fullName: "ARGOUBI EP KHADRAOUI HAJER",
    email: "HAJER.ARGOUBI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1549",
    fullName: "KHEMIRI Akram",
    email: "KHEMIRI.AKRAM@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1550",
    fullName: "BAAZOUZI Wiem",
    email: "wiem.baazouzi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1551",
    fullName: "HICHRI Chaima",
    email: "chaima.hichri1@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1553",
    fullName: "BERRAHAL  Ridha",
    email: "ridha.berrahal@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1555",
    fullName: "ZIDI IMEN",
    email: "IMEN.ZIDI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1556",
    fullName: "SALHI EMNA",
    email: "Emna.SALHI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1557",
    fullName: "HAMMI Zaineb",
    email: "zeineb.hammi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1558",
    fullName: "BEN MHAMED Issam",
    email: "issam.benmhammed@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1560",
    fullName: "FARAH BILEL",
    email: "bilel.farah@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1561",
    fullName: "AOUINI MOURAD",
    email: "mourad.aouini@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1562",
    fullName: "GOSSA LILIA",
    email: "lilia.gossa@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1563",
    fullName: "DAAS FATMA",
    email: "fatma.daas@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1564",
    fullName: "CHARFI EMNA",
    email: "emna.charfi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1565",
    fullName: "KLAI GHASSEN",
    email: "ghassen.klai@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1566",
    fullName: "MALLEK GHASSEN",
    email: "mallek.ghassen@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1568",
    fullName: "GLAA MARIEM",
    email: "mariem.glaa@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1569",
    fullName: "ABDOU MOHAMED BASSEM",
    email: "mohamedbassem.abdou@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1571",
    fullName: "ZOUARI SARRA",
    email: "sarra.zouari@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1572",
    fullName: "HASSEN NADA",
    email: "nada.hassen@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1573",
    fullName: "MAAZOUNE Nadine",
    email: "nadine.maazoun@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1574",
    fullName: "MHALLA MOHAMED FIRAS",
    email: "mohamedfiras.mhalla@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1575",
    fullName: "MAAMAR ISLEM",
    email: "islem.MAAMER@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1576",
    fullName: "TRIFI EYA",
    email: "eya.trifi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1577",
    fullName: "JOUINI Hiba",
    email: "hiba.jouini@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1578",
    fullName: "BEN ROMDHANE Mehdy",
    email: "mehdy.benromdhane@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1579",
    fullName: "HAMDI  Nouha",
    email: "nouha.hamdi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1580",
    fullName: "ELHAZAL Haythem",
    email: "haythem.elhazel@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1581",
    fullName: "ASKRI Mohamed Taher",
    email: "mohamedtaher.askri@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1582",
    fullName: "YAZIDI Amir",
    email: "amir.yazidi1@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1583",
    fullName: "TEKAYA dorra",
    email: "dora.tekaya@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1584",
    fullName: "ALOUI omar",
    email: "omar.aloui@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1586",
    fullName: "KALBOUSSI hazem",
    email: "hazem.kalboussi1@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1587",
    fullName: "RIAHI donia",
    email: "donia.riahi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1588",
    fullName: "BOUZEKRI DHEKRA",
    email: "dhikra.bouzekri@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1590",
    fullName: "DJOBBI HEND",
    email: "Hend.Djebbi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1591",
    fullName: "ARFAOUI IMEN",
    email: "imen.arfaoui@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1592",
    fullName: "AYARI  CHAIMA",
    email: "Ayari.Chaima@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1593",
    fullName: "JENHANI ONS",
    email: "Ons.Jenhani@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1594",
    fullName: "RBII EMNA",
    email: "Emna.Rbii@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1595",
    fullName: "AMMAR KHOULOUD",
    email: "khouloud.ammar@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1596",
    fullName: "THAMRI ESSIA",
    email: "Essia.Thamri@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1597",
    fullName: "HAMDI RABEH",
    email: "Hamdi.Rabeh@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1598",
    fullName: "MBARKI AMAL",
    email: "Amal.Mbarki@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1599",
    fullName: "MILADI SIRAJEDDINE",
    email: "sirajeddine.miladi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1600",
    fullName: "EL HAKIM IMEN",
    email: "imen.elhakim@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1601",
    fullName: "AYARI  SALMA",
    email: "Ayari.Salma@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1602",
    fullName: "LANDOLSI HOUDA",
    email: "houda.landolsi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1603",
    fullName: "HIDRI  WAFA",
    email: "wafa.hidri@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1604",
    fullName: "SETTI  GHADA",
    email: "ghada.setti@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1605",
    fullName: "ayari ICHRAF",
    email: "Ichraf.ayari@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1609",
    fullName: "ENNINE Hanene",
    email: "Hanene.ennine@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1610",
    fullName: "KHECHENA Fares",
    email: "fares.khechana@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1614",
    fullName: "BEN SMIDA Rym",
    email: "rym.bensmida@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1617",
    fullName: "OUALI Zoulaikha",
    email: "zoulaikha.ouali1@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1618",
    fullName: "FARES Hadil",
    email: "hadil.fares@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1622",
    fullName: "SOKRANI Saoussen",
    email: "Saoussen.SOKRANI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1623",
    fullName: "MANNAI Olfa",
    email: "olfa.MANAI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1624",
    fullName: "HAMDI Nawel",
    email: "NAWAL.HAMDI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1625",
    fullName: "MERSNI Amal",
    email: "amal.mersni@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1626",
    fullName: "LATRECH Amel",
    email: "Amel.latrech@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1627",
    fullName: "MIZOUNI Fadwa",
    email: "fadwa.mizouni@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1628",
    fullName: "MAHFOUDHI Ryma",
    email: "ryma.mahfoudhi@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1629",
    fullName: "ABBES Sana",
    email: "SANA.ABBES@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1630",
    fullName: "ZOUAOUI Zeineb",
    email: "Zeineb.ZOUAOUI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1631",
    fullName: "BEN ABDELKADER Mohamed amine",
    email: "Mohamedamine.benabdelkader@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1632",
    fullName: "OUESLATI Wissal",
    email: "wissal.oueslati@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1633",
    fullName: "MBIRKI Anwer",
    email: "ANWER.MBIRKI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1634",
    fullName: "BEN ABDALLAH Ibrahim",
    email: "BENABDALLAH.ibrahim@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1635",
    fullName: "BENNANI Maryem",
    email: "Maryem.Bennani@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1637",
    fullName: "RAJEB Mohamed",
    email: "mohamed.rjab@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1638",
    fullName: "CHEBBI Safa",
    email: "SAFA.CHEBBI@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
  {
    matricule: "1639",
    fullName: "Ridene Asma",
    email: "asma.ridene@esprit.tn",
    role: "ENSEIGNANT",
    updatedAt: new Date(),
    createdAt: new Date(),
    status: "NOLOG",
  },
];

const seedDatabase = async () => {
  console.log("Mongo URI:", process.env.DB_URL);
  console.log("Database Name:", process.env.DB_NAME);
  console.log("Collection Name:", "users");
  const client = new MongoClient(process.env.DB_URL, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });

  try {
    await client.connect();
    const db = client.db(process.env.DB_NAME);
    const collection = db.collection("users");

    const count = await collection.countDocuments();

    if (count === 0) {
      await collection.insertMany(teachers);
      console.log("Database seeded!");
    } else {
      console.log("Data already exists, no need to seed.");
    }
  } catch (error) {
    console.error("Error seeding database:", error);
  } finally {
    await client.close();
  }
};

setTimeout(() => {
  seedDatabase();
}, 5000);
